name: Daily render ping

on:
  schedule:
    - cron: "*/14 * * * *"   # Runs every 15 minutes
  workflow_dispatch:

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://traffic-light-ugoe.onrender.com
